CREATE TABLE todos (
  id VARCHAR(50) PRIMARY KEY NOT NULL,
  title TEXT NOT NULL,
  note TEXT NOT NULL,
  time DATETIME NOT NULL,
  owner VARCHAR(50) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE users (
  id VARCHAR(50) PRIMARY KEY NOT NULL,
  permission VARCHAR(11) CHECK( permission IN ('r', 'r/w') ) NOT NULL DEFAULT 'r',
  username VARCHAR(100) UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);
